// One Stanford Encyclopedia of Philosophy entry per day, chosen from this list by the date.
// Add or remove entries freely. Slugs are the last part of plato.stanford.edu/entries/<slug>/

const SEP = [
  // Philosophy of mind
  ["consciousness", "Consciousness"],
  ["qualia", "Qualia"],
  ["qualia-knowledge", "Qualia: The Knowledge Argument"],
  ["dualism", "Dualism"],
  ["physicalism", "Physicalism"],
  ["functionalism", "Functionalism"],
  ["behaviorism", "Behaviorism"],
  ["mental-causation", "Mental Causation"],
  ["intentionality", "Intentionality"],
  ["mental-representation", "Mental Representation"],
  ["zombies", "Zombies"],
  ["chinese-room", "The Chinese Room Argument"],
  ["turing-test", "The Turing Test"],
  ["computational-mind", "The Computational Theory of Mind"],
  ["embodied-cognition", "Embodied Cognition"],
  ["other-minds", "Other Minds"],
  ["personal-identity", "Personal Identity"],
  ["self-knowledge", "Self-Knowledge"],
  ["pain", "Pain"],
  ["emotion", "Emotion"],
  ["perception-problem", "The Problem of Perception"],
  ["content-externalism", "Externalism About the Mind"],
  ["supervenience", "Supervenience"],
  ["multiple-realizability", "Multiple Realizability"],
  ["connectionism", "Connectionism"],
  ["cognitive-science", "Cognitive Science"],
  ["phenomenology", "Phenomenology"],
  ["freewill", "Free Will"],
  ["moral-responsibility", "Moral Responsibility"],
  // Ethics
  ["ethics-virtue", "Virtue Ethics"],
  ["consequentialism", "Consequentialism"],
  ["ethics-deontological", "Deontological Ethics"],
  ["utilitarianism-history", "The History of Utilitarianism"],
  ["kant-moral", "Kant's Moral Philosophy"],
  ["aristotle-ethics", "Aristotle's Ethics"],
  ["hume-moral", "Hume's Moral Philosophy"],
  ["mill-moral-political", "Mill's Moral and Political Philosophy"],
  ["metaethics", "Metaethics"],
  ["moral-realism", "Moral Realism"],
  ["moral-anti-realism", "Moral Anti-Realism"],
  ["moral-relativism", "Moral Relativism"],
  ["moral-epistemology", "Moral Epistemology"],
  ["moral-luck", "Moral Luck"],
  ["moral-dilemmas", "Moral Dilemmas"],
  ["moral-character", "Moral Character"],
  ["moral-motivation", "Moral Motivation"],
  ["practical-reason", "Practical Reason"],
  ["autonomy-moral", "Autonomy in Moral and Political Philosophy"],
  ["well-being", "Well-Being"],
  ["hedonism", "Hedonism"],
  ["value-theory", "Value Theory"],
  ["rights", "Rights"],
  ["justice", "Justice"],
  ["desert", "Desert"],
  ["death", "Death"],
  ["friendship", "Friendship"],
  ["love", "Love"],
  ["trust", "Trust"],
  ["lying-definition", "The Definition of Lying and Deception"],
  ["ethics-environmental", "Environmental Ethics"],
  ["ethics-business", "Business Ethics"],
  ["neuroethics", "Neuroethics"],
  // Technology and AI
  ["technology", "Philosophy of Technology"],
  ["ethics-ai", "Ethics of Artificial Intelligence and Robotics"],
  ["artificial-intelligence", "Artificial Intelligence"],
  ["logic-ai", "Logic and Artificial Intelligence"],
  ["computing-responsibility", "Computing and Moral Responsibility"],
  ["information", "Information"],
  ["privacy", "Privacy"],
  ["ethics-social-networking", "Social Networking and Ethics"],
  ["ethics-internet-research", "Internet Research Ethics"],
  // Animals
  ["consciousness-animal", "Animal Consciousness"],
  ["cognition-animal", "Animal Cognition"],
  ["moral-animal", "The Moral Status of Animals"],
  ["biodiversity", "Biodiversity"],
];
